### ISSUE TITLE
Strange Error when I try to open AVRDUDESS

### ISSUE THREAD

**Issue by ParasyteGS** [ZakKemble/AVRDUDESS#75]
![image](https://user-images.githubusercontent.com/91819494/229409506-24fac4de-27ed-4aba-9052-4ff0db3cc169.png)

**Comment by ZakKemble** [comment]
Hi, does this still happen with v2.15? https://github.com/ZakKemble/AVRDUDESS/releases/tag/v2.15

**Comment by wwwGPS** [comment]
Hi ZAK. I had no problems running AVRDUDESS any version other than 2.16. An error appears when launching AVRDUDESS 2.16. Runs on Win7. Сan you help?

**Comment by ZakKemble** [comment]
Hey @wwwGPS, I noticed this error just after releasing v2.16 and fixed in this commit https://github.com/ZakKemble/AVRDUDESS/commit/9cf18b5c98471aae96a7c26ef50fd5fe438e537b

I will be releasing v2.17 in the next few days with the fix.

It's caused by having an old version of .NET Framework. v2.0 or v3.5, I think. v4.0 or newer works fine.

**Comment by wwwGPS** [comment]
Thank you! 2.17 works. But there are error "ERROR: Update check failed: The requested security protocol is not supported." in portable version. This is serious problem?

**Comment by ZakKemble** [comment]
It's not a problem, it just can't tell you about newer versions when I release them. You can fix the error by updating .NET Framework - https://dotnet.microsoft.com/en-us/download/dotnet-framework/net481

**Comment by wwwGPS** [comment]
OK!
